### ISSUE TITLE
separa palabra ejemplo: carro => c a r r o

### ISSUE THREAD

**Issue by JonayMedina7** [juanmirod/juanmirod.github.io#2]
saludos, estoy buscando un metodo en javaScript que me ayude a separar la palabra por cada letra y luego introducir un(1) espacio entre cada letra

**Comment by juanmirod** [comment]
Hola Jonay, te recomiendo [mi post sobre split](http://juanmirod.github.io/2017/07/19/javascript-split.html), lo que pides es muy fácil de hacer con split y join:

`'carro'.split('').join(' ')`
